Story2
iO-Academy/2024-sept-rain-frogs-hotel-api pull request #1
Opened 2024-12-10 09:46 UTC by OksanaBakhaieva

2024-12-10 10:16 UTC, ashleycoles requested changes

2024-12-10 10:16 UTC, ashleycoles commented on app/Http/Controllers/RoomAPIController.php
> +       if($room){
You should instead check to see if there is not a room here, and then return your 404 response.

It's always good practice to 'fail early', meaning you should check for failures (like the room not existing) as soon as possible.

This way, you can have something like

```
if (!$room) {
   // return the 404
}

// Return the success response
```

Eliminating the need for the else which does help to make the code simpler

2024-12-10 10:16 UTC, ashleycoles commented on app/Http/Controllers/RoomAPIController.php
> +       $room = Room::find($id);
Here you should really be using with() to load the type straight away - like what was done in story 1

2024-12-10 10:16 UTC, ashleycoles commented on app/Http/Controllers/RoomAPIController.php
> +                    ]
You don't need to do all this stuff, once you add a with to the query you should be able to just put $room in data

2024-12-10 10:16 UTC, ashleycoles commented on app/Models/Room.php
> +    public function type(): BelongsTo
Add empty line above this method

2024-12-10 10:16 UTC, ashleycoles commented on app/Models/Type.php
> +    public function rooms(): HasMany
Add empty line above this method

2024-12-10 10:16 UTC, ashleycoles commented on database/factories/RoomFactory.php
> +            'type_id'=>Type::factory()
Spaces around the => please

2024-12-10 15:33 UTC, Anerkiki commented
We were a little unsure with RoomAPIController.php, but think this is alright?

2024-12-10 16:17 UTC, ashleycoles approved these changes

2024-12-11 09:35 UTC, ashleycoles approved these changes

2024-12-11 09:35 UTC, merged