Story4
iO-Academy/2024-sept-rain-frogs-hotel-api pull request #4
Opened 2024-12-11 15:42 UTC by vivhayles

Pls merge

2024-12-11 16:19 UTC, ashleycoles requested changes

2024-12-11 16:19 UTC, ashleycoles commented on app/Http/Controllers/BookingAPIController.php
> +            })
I believe the ID actually needs to stay - the front-end does (I think) use that information. Even if it doesn't, the rooms do have both id and name in the docs, so you should stick with that

Cool use of map tho, never considered using it for stuff like this.

2024-12-11 16:19 UTC, ashleycoles commented on app/Models/Booking.php
> +    public function room(): BelongsTo
Space above method plz

2024-12-11 16:19 UTC, ashleycoles commented on app/Models/Room.php
> +    public function booking(): HasMany
Space above this method

2024-12-11 16:38 UTC, Anerkiki commented
Resolved comments, not sure how to do/if need to do Changes requested

2024-12-11 17:07 UTC, Anerkiki commented
I think I meant conflicts

2024-12-12 09:47 UTC, ashleycoles approved these changes

2024-12-12 09:47 UTC, merged